### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by szuperaz** [GetStream/stream-chat-angular#584]
## Breaking changes

- [x]  Drop support for Angular12-14, [more info in the docs](https://getstream.io/chat/docs/sdk/angular/basics/angular-version-support/)
- [x] The library used for the context menu is deprecated, we need to migrate to this library: https://www.npmjs.com/package/ngx-float-ui
- [x] All Angular libs should be peer dependencies, instead of regular dependencies (we can't have multiple different versions of an Angular library in an Angular app) #410 
- [x] Remove the deprecated [theme-v1](https://getstream.io/chat/docs/sdk/angular/concepts/themeing/) #541 
- [x] #358 
- [x] Remove all deprecated code
- [x] Match the default reaction set to React's #310
- [x] Remove size and color attributes from the avatar, icon and loading indicator components. All these should be configurable from CSS https://github.com/GetStream/stream-chat-css/issues/84 - solves #569 
- [x] Make icons customizable from CSS (#575 )
- [x] Create new message menu UI to solve mobile usability issues https://github.com/GetStream/stream-chat-css/issues/141 -> this will require reorganizing the reaction components, the new UI:
![Screenshot 2024-04-05 at 10 24 48](https://github.com/GetStream/stream-chat-angular/assets/6690098/160a636f-3afd-44b0-bae2-93767eb8f8e5)
- [x] Update dependencies to the latest version
- [x] By default if an error occurs during channel load, the Observable will emit an error, which will close the stream. Users will have to reload the page to be able to reinitialize the ChannelService. If you don't want the streams to be closed, you can pass options.keepAliveChannels$OnError = true to the init method. In that case the channelQueryState$ stream will emit the status of the latest channel load request. We should remove the `keepAliveChannels$OnError` option, and make it the default behavior, as it's more logical then sending an error to `channels$`

## Major UI changes (that are not breaking)
- [x] Update the edit message UI, the new UI: https://github.com/GetStream/stream-chat-css/issues/125

![Screenshot 2024-04-15 at 11 08 50](https://github.com/GetStream/stream-chat-angular/assets/6690098/95f0d140-9d90-473b-bb07-decb37b482f3)

## Nice to haves

These probably won't make it to v5 as the release is already quite packed, if nothing else, they can be a good starting point for v6

- Evaluate: Separating `ChannelService` into `ChannelListService`, `ActiveChannelService` and `ThreadService`
- Check if Angular Material's customization syntax is something we could use in the future: https://github.com/GetStream/stream-chat-angular/issues/572

**Comment by szuperaz** [comment]
V5 is now the latest stable release of stream-chat-angular
